trigger:
- main

pool:
  # vmImage: 'ubuntu-latest'
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
    includePreviewVersions: true

- script: dotnet restore
  displayName: 'Restaurar dependencias'

# - script: dotnet build --configuration Release
- script: dotnet build DemoDevOps.csproj
  displayName: 'Compilar proyecto'